"""second migration

Revision ID: 7c6b6e7936af
Revises: ba82e6d33f00
Create Date: 2023-01-24 17:42:14.756226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6b6e7936af'
down_revision = 'ba82e6d33f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_4', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('post_5', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_column('post_5')
        batch_op.drop_column('post_4')

    # ### end Alembic commands ###
